CREATE TABLE [info].[SQLInfo]
(
[SQLInfoID] [int] NOT NULL IDENTITY(1, 1),
[DateChecked] [datetime] NULL,
[DateAdded] [datetime] NULL,
[ServerName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[InstanceName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[SQLVersionString] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SQLVersion] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ServicePack] [nvarchar] (3) COLLATE Latin1_General_CI_AS NULL,
[Edition] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ServerType] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[Collation] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[IsHADREnabled] [bit] NULL,
[SQLServiceAccount] [nvarchar] (35) COLLATE Latin1_General_CI_AS NULL,
[SQLService] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[SQLServiceStartMode] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[BAckupDirectory] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[BrowserAccount] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[BrowserStartMode] [nvarchar] (25) COLLATE Latin1_General_CI_AS NULL,
[IsSQLClustered] [bit] NULL,
[ClusterName] [nvarchar] (25) COLLATE Latin1_General_CI_AS NULL,
[ClusterQuorumstate] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[ClusterQuorumType] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[C2AuditMode] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[CostThresholdForParallelism] [tinyint] NULL,
[MaxDegreeOfParallelism] [tinyint] NULL,
[DBMailEnabled] [bit] NULL,
[DefaultBackupCComp] [bit] NULL,
[FillFactor] [tinyint] NULL,
[MaxMem] [int] NULL,
[MinMem] [int] NULL,
[RemoteDacEnabled] [bit] NULL,
[XPCmdShellEnabled] [bit] NULL,
[CommonCriteriaComplianceEnabled] [bit] NULL,
[DefaultFile] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[DefaultLog] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[HADREndpointPort] [int] NULL,
[ErrorLogPath] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[InstallDataDirectory] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[InstallSharedDirectory] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[IsCaseSensitive] [bit] NULL,
[IsFullTextInstalled] [bit] NULL,
[LinkedServer] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[LoginMode] [nvarchar] (20) COLLATE Latin1_General_CI_AS NULL,
[MasterDBLogPath] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[MasterDBPath] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[NamedPipesEnabled] [bit] NULL,
[OptimizeAdhocWorkloads] [bit] NULL,
[InstanceID] [int] NULL,
[AGListener] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[AGs] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[AGListenerPort] [nvarchar] (250) COLLATE Latin1_General_CI_AS NULL,
[AGListenerIPs] [nvarchar] (150) COLLATE Latin1_General_CI_AS NULL,
[AgentServiceAccount] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AgentServiceStartMode] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [info].[SQLInfo] ADD CONSTRAINT [PK__SQL__50A5926BC7005F29] PRIMARY KEY CLUSTERED  ([SQLInfoID]) ON [PRIMARY]
GO
ALTER TABLE [info].[SQLInfo] ADD CONSTRAINT [FK_SQLInfo_InstanceList] FOREIGN KEY ([InstanceID]) REFERENCES [dbo].[InstanceList] ([InstanceID]) ON DELETE CASCADE
GO
